### ISSUE TITLE
undefined method `unconfirmed_email=`

### ISSUE THREAD

**Issue by phyrog** [ontohub/sequel-devise#1]
```
NoMethodError: undefined method `unconfirmed_email=' for #<User:0x0055d13d875398>
from /home/tom/.gem/ruby/2.4.1/gems/devise-4.3.0/lib/devise/models/confirmable.rb:267:in `postpone_email_change_until_confirmation_and_regenerate_confirmation_token'
```

When trying to change the email address.

```ruby
u = User.first
u.email = "foo@bar.com"
u.save # undefined method `unconfirmed_email=` for User ...
```
Same goes for `&:update`.

@eugenk I'm not sure, but I think the problem is in this repo

**Comment by eugenk** [comment]
I'm pretty sure this has nothing to do with this repo, but more with the models or the backend. I just tried your three lines in my `rails c` on the backend `master` and it did not raise an exception.

**Comment by phyrog** [comment]
Just switched to master, tested it, switched back, tested again and the error is gone. Wat. Closing this.
