### ISSUE TITLE
Gem load error

### ISSUE THREAD

**Issue by unrooty** [ontohub/sequel-devise#2]
I have such error when start server: 
`There was an error while trying to load the gem 'sequel-devise'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant Sequel::Plugins::Devise::ClassMethods::Model`

**Comment by unrooty** [comment]
Problem is solved by changing the sequence of gems in the gemfile. Must be
`gem 'sequel-rails'`
`gem 'sequel-devise'`

**Comment by eugenk** [comment]
This should be fixed with #3. Please try version 0.0.12.
